name: Download and Process CSV to JSON

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download_and_process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install pandas

      - name: Create Data Directory
        run: |
          mkdir -p data

      - name: Download Watches CSV
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GID: ${{ secrets.WATCHES_GID }}
        run: |
          SHEET_URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${GID}"
          echo "${SHEET_URL}"
          curl -L -o "data/watches.csv" "${SHEET_URL}"

      - name: Download Movements CSV
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GID: ${{ secrets.MOVEMENTS_GID }}
        run: |
          SHEET_URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${GID}"
          echo "${SHEET_URL}"
          curl -L -o "data/movements.csv" "${SHEET_URL}"

      - name: Convert CSV to JSON
        run: python scripts/csv_to_json.py

      - name: Commit and Push JSON Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
          git commit -m "Files updated by GitHub Action"
            git push
          fi
