name: Update Google Sheet Data to JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          pip install pandas

      - name: Fetch Watches Google Sheet as CSV
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GID: ${{ secrets.WATCHES_GID }}
        run: |
          curl -L -o watches.csv "https://docs.google.com/spreadsheets/d/${{ env.SHEET_ID }}/export?format=csv&gid=${{ env.GID }}"

      - name: Fetch Movements Google Sheet as CSV
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GID: ${{ secrets.MOVEMENTS_GID }}
        run: |
          curl -L -o movements.csv "https://docs.google.com/spreadsheets/d/${{ env.SHEET_ID }}/export?format=csv&gid=${{ env.GID }}"

      - name: Convert CSV files to JSON
        run: |
          python scripts/convert_csv_to_json.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
            git add --all
            git commit -m "Update Google Sheet data"
            git push
          else
            echo "No changes to commit"
            exit 0
          fi

